version: '3.8'

services:
  discordbot:
    image: gonk-disdroid
    restart: unless-stopped
    environment:
      - token=${TOKEN}
      - guild_id=${GUILD_ID}
  # Not really needed unless you want to save stuff!
  # volumes:
      #- ./data:/app/data 
